pipeline {
  agent {
    node { label 'master' }
  }
  stages {
    stage('docker build') {
      steps {
        sh 'docker build -t nextjs_blog .'
      }
    }
    stage('docker run') {
      steps {
        sh 'docker-compose up -d'
      }
    }
  }
}
