pipeline {
  agent {
    node { label 'master' }
  }
  stages {
    stage('install') {
      steps {
        sh 'node -v'
        sh 'echo $PWD'
        sh 'npm install'
      }
    }
    stage('build') {
      steps {
        sh 'rm -rf ${TARGET_DIR}/*'
        sh 'npm run build'
        sh 'cp -R ${PWD}/out/* ${TARGET_DIR}/'
      }
    }
  }
}
